services:
  statnet:
    image: 'ghcr.io/airoflare/statnet:latest'  # Use the latest image of StatNet from the GitHub Container Registry
    container_name: StatNet  # Set the container name to 'StatNet'
    ports:
      - 8080:80 # App listens on port 80 and in most systems port 80 is used by proxies so we are mapping to port 8080 on host system (change this if needed)
    environment:
      - 'ALLOWED_CORS_ORIGINS=${ALLOWED_CORS_ORIGINS}' # Set 'ALLOWED_CORS_ORIGINS' as your domain with https protocol if you are deploying this behind a reverse proxy (it defaults to http://localhost)
    volumes:
      - '/data/statnet/container-names.json:/app/container-names.json:ro'  # Map container names JSON file to the container (read-only mode - sample file is provided on the repo)
      - '/var/run/docker.sock:/var/run/docker.sock:ro'  # Mount the Docker socket to allow interaction with the Docker engine (read-only mode)
      - '/var/lib/docker/volumes/coolify-db:/var/lib/docker/volumes/coolify-db:ro'  # Mount the coolify-db volume to find disk space used by coolify (read-only mode)
      - '/var/lib/docker/volumes/coolify-redis:/var/lib/docker/volumes/coolify-redis:ro'  # Mount the coolify-redis volume to find disk space used by coolify (read-only mode)
      - '/data/coolify:/data/coolify:ro' # Mount the /data/coolify directory to find disk space used by coolify (read-only mode)
      - '/proc:/proc:ro'  # Mount the /proc directory in read-only mode, allowing the app to access host system stats (e.g., CPU, memory - read-only mode)